# CALIDAD DE DATOS PREDICTION

**IMPORTANTE**: Vamos a hacer algunas comprobaciones sobre atipícos por si pudiera aportarnos algo de mejora en el dataset

## IMPORTAR PAQUETES

In [1]:
import numpy as np
import pandas as pd
from janitor import clean_names

#Automcompletar rápido
%config IPCompleter.greedy=True

pd.options.display.float_format = '{:15.2f}'.format

## IMPORTAR LOS DATOS

Sustituir la ruta del proyecto.

In [2]:
ruta_proyecto = 'C:/Users/Oscar/OneDrive - FM4/Escritorio/EVOLVE/Data Science/Proyecto-Master-DataScience-Evolve-OscarFraile'

Sustituir el nombre_fichero_datos.

In [3]:
nombre_fichero_datos = 'trabajo.csv'

Cargar los datos.

In [4]:
ruta_completa = ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_fichero_datos

df = pd.read_csv(ruta_completa,index_col=0).set_index('id')
df

,index,name,host_response_time,host_is_superhost,host_verifications,host_has_profile_pic,host_identity_verified,property_type,room_type,amenities,...,calculated_host_listings_count_shared_rooms,reviews_per_month,precio_m2,bedrooms_disc,accommodates_disc,beds_disc,number_of_reviews_disc,m2,pdi_sol,pisos_rentables
id,,,,,,,,,,,,,,,,,,,,,
30959,2,Beautiful loft in Madrid Center,no response,f,"['email', 'phone']",t,f,Entire loft,Entire home/apt,"[""Breakfast"", ""Heating"", ""Wifi"", ""Smoking allo...",...,0,0.07,6170,01_Una,0-3,1,1-4,50,0.50,1
40916,3,Holiday Apartment Madrid Center,no response,f,"['email', 'phone']",t,f,Entire rental unit,Entire home/apt,"[""Heating"", ""Wifi"", ""Pets allowed"", ""Kitchen"",...",...,0,0.29,6170,01_Una,0-3,3,5-71,50,0.67,1
62423,4,MAGIC ARTISTIC HOUSE IN THE CENTER OF MADRID,within an hour,f,"['email', 'phone']",t,t,Private room in rental unit,Private room,"[""Books and reading material"", ""First aid kit""...",...,0,2.73,6170,01_Una,4,3,71-1136,50,0.62,0
70059,5,Tu hogar en centro de Madrid.,no response,f,"['email', 'phone']",t,t,Entire rental unit,Entire home/apt,"[""Wifi"", ""Window AC unit"", ""Kitchen"", ""Essenti...",...,0,0.36,6170,01_Una,0-3,1,5-71,50,0.99,1
70073,6,Adorable Apartment Malasaña-Gran Via,within an hour,f,"['email', 'phone', 'work_email']",t,t,Entire rental unit,Entire home/apt,"[""Clothing storage: closet and wardrobe"", ""Cit...",...,0,0.22,6170,01_Una,0-3,1,5-71,50,0.65,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1308797105765566482,25867,Elegancia y Comodidad en el Corazón de Madrid,within a few hours,f,"['email', 'phone']",t,t,Entire rental unit,Entire home/apt,"[""Wifi"", ""Kitchen"", ""Hot water"", ""Microwave"", ...",...,0,0.00,4876,01_Una,0-3,1,1-4,50,1.79,0
1308811268356474614,25868,Habitación tranquila,within an hour,f,['phone'],t,t,Private room in rental unit,Private room,"[""Wifi"", ""TV""]",...,0,0.00,3676,01_Una,0-3,1,1-4,50,4.44,0
1308818613904246041,25870,Alquilo habitación por 15 días.,no response,f,"['email', 'phone']",t,t,Private room in rental unit,Private room,"[""Wifi"", ""Kitchen"", ""TV""]",...,0,0.00,6170,01_Una,0-3,1,1-4,50,0.61,0
1308842708819314249,25871,Estudio luminoso y renovado junto a Madrid Río,within a few hours,f,"['email', 'phone']",t,t,Entire rental unit,Entire home/apt,"[""Wifi"", ""Kitchen"", ""Hot water"", ""Microwave"", ...",...,0,0.00,2772,01_Una,0-3,3,1-4,50,1.83,0
1308864880309321118,25872,Precioso y Moderno en el Centro,within an hour,f,"['email', 'phone', 'work_email']",t,t,Entire rental unit,Entire home/apt,"[""Paid parking on premises"", ""Exercise equipme...",...,0,0.00,4850,01_Una,0-3,1,1-4,50,2.96,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18111 entries, 30959 to 1308864880309321118
Data columns (total 58 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   index                                         18111 non-null  int64
 1   name                                          18111 non-null  object
 2   host_response_time                            18111 non-null  object
 3   host_is_superhost                             18111 non-null  object
 4   host_verifications                            18111 non-null  object
 5   host_has_profile_pic                          18111 non-null  object
 6   host_identity_verified                        18111 non-null  object
 7   property_type                                 18111 non-null  object
 8   room_type                                     18111 non-null  object
 9   amenities                                     18111 non-null  object
 10  has_availability                              18111 non-null  object
 11  license                                       18111 non-null  object
 12  instant_bookable                              18111 non-null  object
 13  neighbourhood_group                           18111 non-null  object
 14  host_id                                       18111 non-null  int64
 15  host_since                                    18111 non-null  object
 16  host_response_rate                            18111 non-null  float64
 17  host_acceptance_rate                          18111 non-null  float64
 18  host_listings_count                           18111 non-null  float64
 19  host_total_listings_count                     18111 non-null  float64
 20  latitude                                      18111 non-null  float64
 21  longitude                                     18111 non-null  float64
 22  accommodates                                  18111 non-null  int64
 23  bathrooms                                     18111 non-null  float64
 24  bedrooms                                      18111 non-null  float64
 25  beds                                          18111 non-null  float64
 26  price                                         18111 non-null  int64
 27  minimum_nights                                18111 non-null  int64
 28  maximum_nights                                18111 non-null  int64
 29  availability_30                               18111 non-null  int64
 30  availability_60                               18111 non-null  int64
 31  availability_90                               18111 non-null  int64
 32  availability_365                              18111 non-null  int64
 33  number_of_reviews                             18111 non-null  int64
 34  number_of_reviews_ltm                         18111 non-null  int64
 35  number_of_reviews_l30d                        18111 non-null  int64
 36  first_review                                  18111 non-null  object
 37  last_review                                   18111 non-null  object
 38  review_scores_rating                          18111 non-null  float64
 39  review_scores_accuracy                        18111 non-null  float64
 40  review_scores_cleanliness                     18111 non-null  float64
 41  review_scores_checkin                         18111 non-null  float64
 42  review_scores_communication                   18111 non-null  float64
 43  review_scores_location                        18111 non-null  float64
 44  review_scores_value                           18111 non-null  float64
 45  calculated_host_listings_count                18111 non-null  int64
 46  calculated_host_listings_count_entire_homes   18111 non-null  int64
 47  calculated_host_listings_count_private_rooms  18111 non-null  int64
 48  calculated_host_listings_count_shared_rooms   18111 non-null  int64
 49  reviews_per_month                             18111 non-null  float64
 50  precio_m2                                     18111 non-null  int64
 51  bedrooms_disc                                 18111 non-null  object
 52  accommodates_disc                             18111 non-null  object
 53  beds_disc                                     18111 non-null  object
 54  number_of_reviews_disc                        18111 non-null  object
 55  m2                                            18111 non-null  int64
 56  pdi_sol                                       18111 non-null  float64
 57  pisos_rentables                               18111 non-null  int64
dtypes: float64(18), int64(20), object(20)
memory usage: 8.2+ MB

## VALORES ÚNICOS

### Identificación

In [6]:
df.nunique().sort_values()

pisos_rentables                                     2
host_is_superhost                                   2
instant_bookable                                    2
host_has_profile_pic                                2
host_identity_verified                              2
license                                             2
has_availability                                    2
accommodates_disc                                   3
beds_disc                                           3
room_type                                           3
number_of_reviews_disc                              3
bedrooms_disc                                       5
host_response_time                                  5
m2                                                  6
host_verifications                                  7
calculated_host_listings_count_shared_rooms        13
bedrooms                                           15
accommodates                                       16
bathrooms                                          17
beds                                               17
number_of_reviews_l30d                             18
precio_m2                                          21
neighbourhood_group                                21
calculated_host_listings_count_private_rooms       30
availability_30                                    31
property_type                                      53
availability_60                                    61
calculated_host_listings_count_entire_homes        68
calculated_host_listings_count                     71
host_response_rate                                 83
minimum_nights                                     84
availability_90                                    91
host_acceptance_rate                              100
host_listings_count                               109
review_scores_checkin                             130
host_total_listings_count                         133
review_scores_communication                       137
review_scores_accuracy                            142
review_scores_location                            145
number_of_reviews_ltm                             155
review_scores_cleanliness                         157
review_scores_rating                              158
maximum_nights                                    163
review_scores_value                               164
availability_365                                  366
price                                             540
number_of_reviews                                 543
reviews_per_month                                 911
last_review                                      2569
first_review                                     3612
host_since                                       3872
host_id                                          9336
longitude                                       11887
latitude                                        12307
amenities                                       15929
name                                            17173
pdi_sol                                         17390
index                                           18111
dtype: int64

## SEPARAR NUMÉRICAS Y CATEGÓRICAS

### Categóricas

In [7]:
cat = df.select_dtypes(exclude = 'number').copy()

### Numéricas

In [8]:
num = df.select_dtypes(include='number').copy()

## GESTIÓN DE CATEGÓRICAS

### Nulos

#### Identificación

In [9]:
#Es importante investigar bien los datos que aparecen como nulos porque puede que estén mal identificados como nulos
cat.isna().sum().sort_values(ascending = False)

name                      0
host_response_time        0
beds_disc                 0
accommodates_disc         0
bedrooms_disc             0
last_review               0
first_review              0
host_since                0
neighbourhood_group       0
instant_bookable          0
license                   0
has_availability          0
amenities                 0
room_type                 0
property_type             0
host_identity_verified    0
host_has_profile_pic      0
host_verifications        0
host_is_superhost         0
number_of_reviews_disc    0
dtype: int64

### Atípicos

#### Categorías poco frecuentes

##### Identificación

In [10]:
for variable in cat:
    print(variable + '\n')
    print(cat[variable].value_counts(dropna = False))
    print('\n\n')

name

Habitación con baño privado                           23
Vibrating Hostel in Tetuán close to S. Bernabeu       22
Habitación en Madrid                                  16
H Individual In Reformed Residence has wifi & cent    16
Habitación privada                                    15
                                                      ..
Luxury One-Bedroom Corner Apartment                    1
Apartamento Goya Duplex 3 hab MadridCentro Garaje      1
Bright apartment Oshun in Madrid Norte E               1
Arenal Suites Gran Vía Estudio (7)                     1
Precioso y Moderno en el Centro                        1
Name: name, Length: 17173, dtype: int64



host_response_time

within an hour        10670
no response            3489
within a few hours     2016
within a day           1158
a few days or more      778
Name: host_response_time, dtype: int64



host_is_superhost

f    13359
t     4752
Name: host_is_superhost, dtype: int64



host_verifications

['email', 'phone']                  13836
['email', 'phone', 'work_email']     1932
['phone']                            1865
['phone', 'work_email']               417
['email']                              43
['No']                                 16
['email', 'work_email']                 2
Name: host_verifications, dtype: int64



host_has_profile_pic

t    17541
f      570
Name: host_has_profile_pic, dtype: int64



host_identity_verified

t    16155
f     1956
Name: host_identity_verified, dtype: int64



property_type

Entire rental unit                    10852
Private room in rental unit            4511
Private room in home                    561
Entire condo                            424
Entire loft                             382
Entire home                             245
Private room in condo                   221
Entire serviced apartment               213
Private room in casa particular         122
Private room in bed and breakfast        77
Shared room in rental unit               61
Shared room in bed and breakfast         42
Private room                             34
Private room in guesthouse               30
Private room in loft                     27
Private room in guest suite              27
Private room in townhouse                25
Shared room in guesthouse                24
Private room in chalet                   22
Entire vacation home                     20
Entire guest suite                       20
Private room in serviced apartment       19
Camper/RV                                14
Entire townhouse                         11
Shared room in home                      11
Casa particular                          11
Private room in villa                    10
Entire guesthouse                        10
Tiny home                                10
Entire place                              9
Entire chalet                             8
Private room in tiny home                 7
Private room in vacation home             6
Entire villa                              6
Private room in floor                     5
Shared room in loft                       4
Entire home/apt                           4
Entire cabin                              3
Private room in cave                      3
Private room in dome                      2
Private room in earthen home              2
Shared room                               2
Shared room in condo                      2
Shared room in casa particular            2
Floor                                     2
Private room in cottage                   1
Yurt                                      1
Private room in barn                      1
Shared room in resort                     1
Private room in bungalow                  1
Private room in ryokan                    1
Private room in tent                      1
Entire bungalow                           1
Name: property_type, dtype: int64



room_type

Entire home/apt    12246
Private room        5716
Shared room          149
Name: room_type, dtype: int64



amenities

["Wifi", "Kitchen", "TV", "Washer", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                90
["Hangers", "Clothing storage", "Heating", "Wifi", "Bed linens", "Kitchen", "TV", "Essentials", "Washer", "Dedicated workspace", "Cooking basics", "Host greets you", "Hot water"]                                                                                                                                                                                                                                                                                                                                                                                                                                                     64
["Wifi", "Kitchen", "TV", "Washer", "Dedicated workspace", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         58
["Wifi", "Kitchen", "TV", "Washer"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    51
["Wifi", "Kitchen", "Dedicated workspace", "Washer", "Lock on bedroom door"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           48
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ..
["Ethernet connection", "Fast wifi \u2013 282 Mbps", "First aid kit", "Kitchen", "Essentials", "Stove", "Hot water", "Iron", "Microwave", "Hangers", "Dining table", "Heating", "Shower gel", "TV", "Washer", "Carbon monoxide alarm", "Fire extinguisher", "High chair", "Paid parking garage off premises", "Shampoo", "Smoke alarm", "Long term stays allowed", "Body soap", "Bathtub", "Hair dryer", "Bed linens", "Indoor fireplace", "Freezer", "Coffee maker", "Laundromat nearby", "Dishes and silverware", "Cooking basics", "Wine glasses", "Refrigerator", "Air conditioning", "Crib"]                                       1
["Ethernet connection", "Wifi", "AC - split type ductless system", "Kitchen", "Essentials", "Hot water", "Iron", "Paid street parking off premises", "Microwave", "Electric stove", "Hangers", "Extra pillows and blankets", "Dining table", "Toaster", "Hot water kettle", "Fire extinguisher", "42 inch HDTV", "Smoke alarm", "Wine glasses", "Long term stays allowed", "Hair dryer", "Host greets you", "Freezer", "Heating - split type ductless system", "Laundromat nearby", "Dishwasher", "Coffee maker: drip coffee maker, Nespresso", "Cooking basics", "Room-darkening shades", "Refrigerator", "Dishes and silverware"]     1
["Wifi", "Kitchen", "Essentials", "Stove", "Smart lock", "Hot water", "Iron", "Paid parking off premises", "Microwave", "Hangers", "Portable fans", "Heating", "Toaster", "TV", "Washer", "Fire extinguisher", "Patio or balcony", "Hair dryer", "Coffee maker", "Blender", "Dishwasher", "Oven", "Self check-in", "Cooking basics", "Refrigerator", "Dishes and silverware"]                                                                                                                                                                                                                                                           1
["Ethernet connection", "Wifi", "Clothing storage: closet", "Kitchen", "Essentials", "Hot water", "Iron", "Microwave", "Hangers", "Heating", "Toaster", "Hot water kettle", "TV", "Washer", "Ceiling fan", "Teka  stainless steel oven", "Wine glasses", "Long term stays allowed", "Hair dryer", "Bed linens", "Teka refrigerator", "Laundromat nearby", "Free street parking", "Dishes and silverware", "Cooking basics", "Room-darkening shades", "Air conditioning"]                                                                                                                                                                1
["Paid parking on premises", "Exercise equipment", "Smoke alarm", "Pool", "Exterior security cameras on property", "Wifi", "Smoking allowed", "Kitchen", "TV", "Washer", "Carbon monoxide alarm", "Fire extinguisher", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                              1
Name: amenities, Length: 15929, dtype: int64



has_availability

yes    17047
no      1064
Name: has_availability, dtype: int64



license

no     16308
yes     1803
Name: license, dtype: int64



instant_bookable

f    10874
t     7237
Name: instant_bookable, dtype: int64



neighbourhood_group

Centro                7364
Salamanca             1274
Chamberí              1175
Tetuán                1112
Arganzuela             979
Carabanchel            702
Ciudad Lineal          684
Retiro                 653
Chamartín              613
Puente de Vallecas     566
Moncloa                466
Latina                 461
Usera                  435
San Blas               399
Hortaleza              360
Fuencarral             265
Villaverde             182
Barajas                138
Moratalaz              126
Villa de Vallecas      100
Vicálvaro               57
Name: neighbourhood_group, dtype: int64



host_since

2019-09-03 00:00:00.000000    231
2020-11-30 00:00:00.000000    230
2020-05-15 00:00:00.000000    222
2021-12-30 00:00:00.000000    214
2023-06-07 00:00:00.000000    192
                             ...
2012-08-16 00:00:00.000000      1
2021-08-08 00:00:00.000000      1
2013-10-31 00:00:00.000000      1
2020-05-12 00:00:00.000000      1
2024-04-05 00:00:00.000000      1
Name: host_since, Length: 3872, dtype: int64



first_review

2021-12-30 00:00:00.000000    187
2020-05-15 00:00:00.000000    156
2022-07-28 00:00:00.000000     89
2023-06-07 00:00:00.000000     88
2024-05-08 00:00:00.000000     85
                             ...
2017-07-12 00:00:00.000000      1
2017-11-29 00:00:00.000000      1
2014-03-11 00:00:00.000000      1
2014-03-31 00:00:00.000000      1
2015-03-07 00:00:00.000000      1
Name: first_review, Length: 3612, dtype: int64



last_review

2024-12-08 00:00:00.000000    846
2024-11-24 00:00:00.000000    574
2024-12-09 00:00:00.000000    553
2024-12-01 00:00:00.000000    543
2024-11-25 00:00:00.000000    374
                             ...
2019-02-14 00:00:00.000000      1
2011-04-10 00:00:00.000000      1
2023-03-28 00:00:00.000000      1
2019-02-05 00:00:00.000000      1
2016-08-21 00:00:00.000000      1
Name: last_review, Length: 2569, dtype: int64



bedrooms_disc

01_Una             9782
02_Dos             3768
00_Estudio         2762
03_Tres            1301
04_Cuatro o mas     498
Name: bedrooms_disc, dtype: int64



accommodates_disc

0-3     10719
4        4381
4-16     3011
Name: accommodates_disc, dtype: int64



beds_disc

1       9096
3       7361
3-19    1654
Name: beds_disc, dtype: int64



number_of_reviews_disc

1-4        9164
5-71       5324
71-1136    3623
Name: number_of_reviews_disc, dtype: int64

##### Función para agrupar categorías raras en 'OTROS'

In [11]:
def agrupar_cat_raras(variable, criterio = 0.05):
    #Calcula las frecuencias
    frecuencias = variable.value_counts(normalize=True)
    #Identifica las que están por debajo del criterio
    temp = [cada for cada in frecuencias.loc[frecuencias < criterio].index.values]
    #Las recodifica en 'OTROS'
    temp2 = np.where(variable.isin(temp),'OTROS',variable)
    #Devuelve el resultado
    return(temp2)

##### Variables a imputar

In [12]:
var_imputar_cat_raras = ['property_type']

##### Aplicar

In [13]:
for variable in var_imputar_cat_raras:
    cat[variable] = agrupar_cat_raras(cat[variable],criterio = 0.02)

In [14]:
cat['host_verifications'] = np.where(cat.host_verifications == "['email', 'work_email']", "['email']", cat.host_verifications)

Comprobamos los cambios aplicados

In [15]:
for variable in cat:
    print(variable + '\n')
    print(cat[variable].value_counts(dropna = False))
    print('\n\n')

name

Habitación con baño privado                           23
Vibrating Hostel in Tetuán close to S. Bernabeu       22
Habitación en Madrid                                  16
H Individual In Reformed Residence has wifi & cent    16
Habitación privada                                    15
                                                      ..
Luxury One-Bedroom Corner Apartment                    1
Apartamento Goya Duplex 3 hab MadridCentro Garaje      1
Bright apartment Oshun in Madrid Norte E               1
Arenal Suites Gran Vía Estudio (7)                     1
Precioso y Moderno en el Centro                        1
Name: name, Length: 17173, dtype: int64



host_response_time

within an hour        10670
no response            3489
within a few hours     2016
within a day           1158
a few days or more      778
Name: host_response_time, dtype: int64



host_is_superhost

f    13359
t     4752
Name: host_is_superhost, dtype: int64



host_verifications

['email', 'phone']                  13836
['email', 'phone', 'work_email']     1932
['phone']                            1865
['phone', 'work_email']               417
['email']                              45
['No']                                 16
Name: host_verifications, dtype: int64



host_has_profile_pic

t    17541
f      570
Name: host_has_profile_pic, dtype: int64



host_identity_verified

t    16155
f     1956
Name: host_identity_verified, dtype: int64



property_type

Entire rental unit             10852
Private room in rental unit     4511
OTROS                           1381
Private room in home             561
Entire condo                     424
Entire loft                      382
Name: property_type, dtype: int64



room_type

Entire home/apt    12246
Private room        5716
Shared room          149
Name: room_type, dtype: int64



amenities

["Wifi", "Kitchen", "TV", "Washer", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                90
["Hangers", "Clothing storage", "Heating", "Wifi", "Bed linens", "Kitchen", "TV", "Essentials", "Washer", "Dedicated workspace", "Cooking basics", "Host greets you", "Hot water"]                                                                                                                                                                                                                                                                                                                                                                                                                                                     64
["Wifi", "Kitchen", "TV", "Washer", "Dedicated workspace", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         58
["Wifi", "Kitchen", "TV", "Washer"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    51
["Wifi", "Kitchen", "Dedicated workspace", "Washer", "Lock on bedroom door"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           48
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ..
["Ethernet connection", "Fast wifi \u2013 282 Mbps", "First aid kit", "Kitchen", "Essentials", "Stove", "Hot water", "Iron", "Microwave", "Hangers", "Dining table", "Heating", "Shower gel", "TV", "Washer", "Carbon monoxide alarm", "Fire extinguisher", "High chair", "Paid parking garage off premises", "Shampoo", "Smoke alarm", "Long term stays allowed", "Body soap", "Bathtub", "Hair dryer", "Bed linens", "Indoor fireplace", "Freezer", "Coffee maker", "Laundromat nearby", "Dishes and silverware", "Cooking basics", "Wine glasses", "Refrigerator", "Air conditioning", "Crib"]                                       1
["Ethernet connection", "Wifi", "AC - split type ductless system", "Kitchen", "Essentials", "Hot water", "Iron", "Paid street parking off premises", "Microwave", "Electric stove", "Hangers", "Extra pillows and blankets", "Dining table", "Toaster", "Hot water kettle", "Fire extinguisher", "42 inch HDTV", "Smoke alarm", "Wine glasses", "Long term stays allowed", "Hair dryer", "Host greets you", "Freezer", "Heating - split type ductless system", "Laundromat nearby", "Dishwasher", "Coffee maker: drip coffee maker, Nespresso", "Cooking basics", "Room-darkening shades", "Refrigerator", "Dishes and silverware"]     1
["Wifi", "Kitchen", "Essentials", "Stove", "Smart lock", "Hot water", "Iron", "Paid parking off premises", "Microwave", "Hangers", "Portable fans", "Heating", "Toaster", "TV", "Washer", "Fire extinguisher", "Patio or balcony", "Hair dryer", "Coffee maker", "Blender", "Dishwasher", "Oven", "Self check-in", "Cooking basics", "Refrigerator", "Dishes and silverware"]                                                                                                                                                                                                                                                           1
["Ethernet connection", "Wifi", "Clothing storage: closet", "Kitchen", "Essentials", "Hot water", "Iron", "Microwave", "Hangers", "Heating", "Toaster", "Hot water kettle", "TV", "Washer", "Ceiling fan", "Teka  stainless steel oven", "Wine glasses", "Long term stays allowed", "Hair dryer", "Bed linens", "Teka refrigerator", "Laundromat nearby", "Free street parking", "Dishes and silverware", "Cooking basics", "Room-darkening shades", "Air conditioning"]                                                                                                                                                                1
["Paid parking on premises", "Exercise equipment", "Smoke alarm", "Pool", "Exterior security cameras on property", "Wifi", "Smoking allowed", "Kitchen", "TV", "Washer", "Carbon monoxide alarm", "Fire extinguisher", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                              1
Name: amenities, Length: 15929, dtype: int64



has_availability

yes    17047
no      1064
Name: has_availability, dtype: int64



license

no     16308
yes     1803
Name: license, dtype: int64



instant_bookable

f    10874
t     7237
Name: instant_bookable, dtype: int64



neighbourhood_group

Centro                7364
Salamanca             1274
Chamberí              1175
Tetuán                1112
Arganzuela             979
Carabanchel            702
Ciudad Lineal          684
Retiro                 653
Chamartín              613
Puente de Vallecas     566
Moncloa                466
Latina                 461
Usera                  435
San Blas               399
Hortaleza              360
Fuencarral             265
Villaverde             182
Barajas                138
Moratalaz              126
Villa de Vallecas      100
Vicálvaro               57
Name: neighbourhood_group, dtype: int64



host_since

2019-09-03 00:00:00.000000    231
2020-11-30 00:00:00.000000    230
2020-05-15 00:00:00.000000    222
2021-12-30 00:00:00.000000    214
2023-06-07 00:00:00.000000    192
                             ...
2012-08-16 00:00:00.000000      1
2021-08-08 00:00:00.000000      1
2013-10-31 00:00:00.000000      1
2020-05-12 00:00:00.000000      1
2024-04-05 00:00:00.000000      1
Name: host_since, Length: 3872, dtype: int64



first_review

2021-12-30 00:00:00.000000    187
2020-05-15 00:00:00.000000    156
2022-07-28 00:00:00.000000     89
2023-06-07 00:00:00.000000     88
2024-05-08 00:00:00.000000     85
                             ...
2017-07-12 00:00:00.000000      1
2017-11-29 00:00:00.000000      1
2014-03-11 00:00:00.000000      1
2014-03-31 00:00:00.000000      1
2015-03-07 00:00:00.000000      1
Name: first_review, Length: 3612, dtype: int64



last_review

2024-12-08 00:00:00.000000    846
2024-11-24 00:00:00.000000    574
2024-12-09 00:00:00.000000    553
2024-12-01 00:00:00.000000    543
2024-11-25 00:00:00.000000    374
                             ...
2019-02-14 00:00:00.000000      1
2011-04-10 00:00:00.000000      1
2023-03-28 00:00:00.000000      1
2019-02-05 00:00:00.000000      1
2016-08-21 00:00:00.000000      1
Name: last_review, Length: 2569, dtype: int64



bedrooms_disc

01_Una             9782
02_Dos             3768
00_Estudio         2762
03_Tres            1301
04_Cuatro o mas     498
Name: bedrooms_disc, dtype: int64



accommodates_disc

0-3     10719
4        4381
4-16     3011
Name: accommodates_disc, dtype: int64



beds_disc

1       9096
3       7361
3-19    1654
Name: beds_disc, dtype: int64



number_of_reviews_disc

1-4        9164
5-71       5324
71-1136    3623
Name: number_of_reviews_disc, dtype: int64

## 10. GESTIÓN DE NUMÉRICAS

### Estadísticos

In [16]:
num.describe().T

,count,mean,std,min,25%,50%,75%,max
index,18111.00,12924.27,7458.25,2.00,6447.50,12981.00,19335.00,25872.00
host_id,18111.00,247326137.81,203658672.72,7952.00,47554470.00,206493136.00,443065412.00,666283584.00
host_response_rate,18111.00,74.54,40.81,0.00,64.00,100.00,100.00,100.00
host_acceptance_rate,18111.00,84.70,24.40,0.00,82.00,97.00,100.00,100.00
host_listings_count,18111.00,50.56,133.81,1.00,1.00,3.00,24.00,3251.00
host_total_listings_count,18111.00,61.38,187.19,1.00,2.00,5.00,31.00,7970.00
latitude,18111.00,40.42,0.02,40.33,40.41,40.42,40.43,40.54
longitude,18111.00,-3.69,0.03,-3.83,-3.71,-3.70,-3.68,-3.55
accommodates,18111.00,3.17,1.91,1.00,2.00,3.00,4.00,16.00
bathrooms,18111.00,1.28,0.61,0.00,1.00,1.00,1.50,15.00
bedrooms,18111.00,1.30,0.99,0.00,1.00,1.00,2.00,14.00
beds,18111.00,1.86,1.26,0.00,1.00,1.00,2.00,19.00
price,18111.00,118.45,101.55,20.00,65.00,98.00,140.00,2000.00
minimum_nights,18111.00,8.35,29.14,1.00,1.00,2.00,4.00,1125.00
maximum_nights,18111.00,522.73,421.10,1.00,300.00,365.00,1125.00,1125.00
availability_30,18111.00,9.73,9.73,0.00,0.00,8.00,16.00,30.00
availability_60,18111.00,24.55,21.05,0.00,0.00,24.00,43.00,60.00
availability_90,18111.00,40.99,32.96,0.00,0.00,44.00,71.00,90.00
availability_365,18111.00,163.41,134.75,0.00,17.00,157.00,300.00,365.00
number_of_reviews,18111.00,47.37,87.22,0.00,1.00,11.00,53.00,1018.00
number_of_reviews_ltm,18111.00,14.59,22.01,0.00,0.00,4.00,21.00,302.00
number_of_reviews_l30d,18111.00,1.05,1.84,0.00,0.00,0.00,2.00,24.00
review_scores_rating,18111.00,3.71,1.92,0.00,4.00,4.68,4.89,5.00
review_scores_accuracy,18111.00,3.75,1.94,0.00,4.06,4.75,4.92,5.00
review_scores_cleanliness,18111.00,3.73,1.93,0.00,4.00,4.72,4.91,5.00
review_scores_checkin,18111.00,3.79,1.95,0.00,4.23,4.80,4.95,5.00
review_scores_communication,18111.00,3.79,1.96,0.00,4.20,4.83,4.97,5.00
review_scores_location,18111.00,3.78,1.94,0.00,4.17,4.79,4.95,5.00
review_scores_value,18111.00,3.63,1.89,0.00,4.00,4.58,4.80,5.00
calculated_host_listings_count,18111.00,35.71,80.79,1.00,1.00,3.00,18.00,343.00
calculated_host_listings_count_entire_homes,18111.00,31.89,79.44,0.00,0.00,1.00,11.00,343.00
calculated_host_listings_count_private_rooms,18111.00,3.68,16.95,0.00,0.00,0.00,1.00,175.00
calculated_host_listings_count_shared_rooms,18111.00,0.14,1.82,0.00,0.00,0.00,0.00,38.00
reviews_per_month,18111.00,1.49,1.89,0.00,0.06,0.76,2.31,23.65
precio_m2,18111.00,5327.99,1521.77,2070.00,4536.00,6170.00,6170.00,7846.00
m2,18111.00,57.75,18.50,40.00,50.00,50.00,70.00,150.00
pdi_sol,18111.00,2.78,2.46,0.00,0.83,2.01,4.08,14.53
pisos_rentables,18111.00,0.69,0.46,0.00,0.00,1.00,1.00,1.00

### 10.2. Nulos

#### 10.2.1. Identificación

In [17]:
num.isna().sum().sort_values(ascending = False)

index                                           0
review_scores_value                             0
number_of_reviews_l30d                          0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
calculated_host_listings_count                  0
host_id                                         0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
precio_m2                                       0
m2                                              0
pdi_sol                                         0
number_of_reviews_ltm                           0
number_of_reviews                               0
availability_365                                0
availability_90                                 0
host_response_rate                              0
host_acceptance_rate                            0
host_listings_count                             0
host_total_listings_count                       0
latitude                                        0
longitude                                       0
accommodates                                    0
bathrooms                                       0
bedrooms                                        0
beds                                            0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
availability_30                                 0
availability_60                                 0
pisos_rentables                                 0
dtype: int64

## GUARDAR DATASETS TRAS CALIDAD DE DATOS

Guardamos los avances en df, cat y num con un sufijo para poder guardar o recuperar avances del proyecto.

En formato pickle para no perder las modificaciones de metadatos.

### Definir los nombres de los archivos

In [18]:
ruta_trabajo = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'trabajo_resultado_calidad.pickle'
ruta_cat = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'cat_resultado_calidad.pickle'
ruta_num = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'num_resultado_calidad.pickle'

### Guardar los archivos

In [19]:
df.to_pickle(ruta_trabajo)
cat.to_pickle(ruta_cat)
num.to_pickle(ruta_num)