# MERGE DE PERIODOS

Este notebook combina todos los CSV de salida de `05_Resultados` en un único dataset para su visualización en Power BI.

Para añadir un nuevo periodo:
1. Ejecuta el notebook `17_X_Aplicacion_NuevoPeriodo.ipynb` con los datos nuevos
2. Asegúrate de que el CSV resultante tiene la columna `periodo` con el valor correcto
3. Copia el CSV a `05_Resultados`
4. Ejecuta este notebook
5. Abre Power BI y dale a **Actualizar**

## SET UP

In [2]:
import pandas as pd
import os
import glob

## RUTAS

In [3]:
ruta_proyecto = 'C:/Users/Oscar/OneDrive - FM4/Escritorio/EVOLVE/Data Science/Proyecto-Master-DataScience-Evolve-OscarFraile'
ruta_resultados = ruta_proyecto + '/05_Resultados/'

## CARGA Y MERGE

Lee automáticamente todos los CSV de `05_Resultados` que tengan la columna `periodo`.

In [4]:
ficheros = glob.glob(ruta_resultados + 'airbnb_*.csv')
print(f'Ficheros encontrados: {len(ficheros)}')
for f in ficheros:
    print(' -', os.path.basename(f))

Ficheros encontrados: 3
 - airbnb_dic24.csv
 - airbnb_jun25.csv
 - airbnb_mar25.csv

In [5]:
dfs = []
for f in ficheros:
    df_temp = pd.read_csv(f)
    if 'periodo' not in df_temp.columns:
        print(f'AVISO: {os.path.basename(f)} no tiene columna periodo — se omite')
        continue
    dfs.append(df_temp)
    print(f'{os.path.basename(f)}: {df_temp.shape[0]} filas — periodo: {df_temp.periodo.unique()}')

df_all = pd.concat(dfs, ignore_index=True)
df_all['orden_periodo'] = df_all['periodo'].map({'Dic24': 1, 'Mar25': 2, 'Jun25': 3})
print(f'\nDataset combinado: {df_all.shape}')
df_all.periodo.value_counts()

airbnb_dic24.csv: 24045 filas — periodo: ['Dic24']
airbnb_jun25.csv: 25098 filas — periodo: ['Jun25']
airbnb_mar25.csv: 24441 filas — periodo: ['Mar25']

Dataset combinado: (73584, 72)

Jun25    25098
Mar25    24441
Dic24    24045
Name: periodo, dtype: int64

In [6]:
pd.set_option('display.max_columns', None)
df_all

,accommodates,availability_30,availability_365,availability_90,bedrooms,bed,calculated_host_listings_count,has_availability,host_response_rate,host_response_time,instant_bookable,maximum_nights,neighbourhood_group,price,property_type,room_type,license,bathrooms,air,allowed,cleaning,hot water iron,iron,microwave,parking,refrigerator,shampoo,tv washer,wifi kitchen,and silverware,body,clothing,clothing storage,coffee,elevator,hair,host_identity_verified,host_verifications,kitchen essentials,allowed.1,basics,beds,dryer bed,hair dryer,maker,microwave hangers,oven,stove,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,host_is_superhost,bathrooms_text,precio_m2,latitude,longitude,amenities,number_of_reviews,rentabilidad_predicha,rentable,precio_total,m2,ingresos_brutos_anuales,beneficio_neto_anual,precio_estimado,rentabilidad_anual_pct,periodo,orden_periodo
0,1,0,144,0,1.0,1,2,yes,0.0,no response,f,40,Latina,31.0,Private room in rental unit,Private room,no,1.0,1,0,0,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,t,"['email', 'phone']",1,0,1,1.0,1,1,1,1,1,0,4.58,4.72,4.56,4.75,4.82,4.21,4.67,f,1.0,2772,40.403810,-3.741300,"[""First aid kit"", ""Wifi"", ""Kitchen"", ""Essentia...",33,0.995983,True,31.00,50,5138.250,3596.77,138600,2.60,Dic24,1
1,2,0,0,0,1.0,0,3,no,0.0,no response,f,180,Centro,106.0,Entire rental unit,Entire home/apt,no,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,f,"['email', 'phone']",0,0,0,1.0,0,0,0,0,0,0,4.63,4.71,4.88,4.82,4.78,4.90,4.69,f,1.0,6170,40.414760,-3.704180,"[""Heating"", ""Wifi"", ""TV with standard cable"", ...",172,1.000000,True,106.00,50,29017.500,20312.25,308500,6.58,Dic24,1
2,2,0,0,0,1.0,0,1,no,0.0,no response,f,730,Centro,106.0,Entire loft,Entire home/apt,no,1.0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,f,"['email', 'phone']",0,1,0,1.0,0,0,0,0,0,0,4.38,4.14,4.38,4.63,4.63,4.88,4.25,f,1.0,6170,40.412590,-3.701050,"[""Breakfast"", ""Heating"", ""Wifi"", ""Smoking allo...",8,1.000000,True,106.00,50,29017.500,20312.25,308500,6.58,Dic24,1
3,3,0,0,0,1.0,0,3,no,0.0,no response,f,180,Centro,122.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,f,"['email', 'phone']",0,1,0,2.0,0,0,0,0,0,0,4.65,4.69,4.90,4.85,4.79,4.88,4.55,f,1.0,6170,40.422470,-3.705770,"[""Heating"", ""Wifi"", ""Pets allowed"", ""Kitchen"",...",49,1.000000,True,122.00,50,33397.500,23378.25,308500,7.58,Dic24,1
4,4,13,332,59,1.0,0,3,yes,100.0,within an hour,f,30,Centro,69.0,Private room in rental unit,Private room,no,1.5,0,1,1,1,1,0,0,1,1,0,0,1,1,0,0,0,0,1,t,"['email', 'phone']",1,1,1,2.0,0,1,0,0,0,0,4.64,4.78,4.42,4.79,4.85,4.97,4.58,f,1.5,6170,40.418840,-3.696550,"[""Books and reading material"", ""First aid kit""...",219,0.000008,False,80.94,50,2003.265,1402.29,308500,0.45,Dic24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73579,2,20,355,80,1.0,0,45,yes,73.0,within a few hours,f,365,Tetuán,67.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,1,0,1.0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1.0,4536,40.464951,-3.704578,"[""Air conditioning"", ""Pets allowed"", ""Wifi"", ""...",0,0.000018,False,67.00,50,14271.000,9989.70,226800,4.40,Mar25,2
73580,2,25,360,85,1.0,0,45,yes,73.0,within a few hours,f,365,Tetuán,63.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,1,0,1.0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1.0,4536,40.468355,-3.706939,"[""Air conditioning"", ""Pets allowed"", ""Wifi"", ""...",0,0.000009,False,63.00,50,13608.000,9525.60,226800,4.20,Mar25,2
73581,3,0,0,0,1.0,1,3,yes,100.0,within an hour,f,365,Hortaleza,103.0,Entire rental unit,Entire home/apt,no,1.0,1,1,1,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,t,"['email', 'phone']",0,1,1,2.0,0,1,1,0,1,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,t,1.0,4368,40.464110,-3.647130,"[""Cleaning available during stay"", ""Wifi"", ""Wi...",0,1.000000,True,103.00,50,0.000,0.00,218400,0.00,Mar25,2
73582,5,30,365,90,2.0,0,45,yes,73.0,within a few hours,f,365,Carabanchel,100.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,1,0,3.0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1.0,2712,40.395983,-3.730953,"[""Pets allowed"", ""Kitchen"", ""TV"", ""Air conditi...",0,0.000075,False,100.00,70,21900.000,15330.00,189840,8.08,Mar25,2
73583,3,3,3,3,1.0,0,45,yes,73.0,within a few hours,f,365,Carabanchel,66.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,1,0,1.0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1.0,2712,40.395621,-3.731533,"[""Pets allowed"", ""Kitchen"", ""TV"", ""Air conditi...",0,1.000000,True,66.00,50,118.800,83.16,135600,0.06,Mar25,2

In [7]:
df_all.latitude.info()

<class 'pandas.core.series.Series'>
RangeIndex: 73584 entries, 0 to 73583
Series name: latitude
Non-Null Count  Dtype
--------------  -----
73584 non-null  float64
dtypes: float64(1)
memory usage: 575.0 KB

## EXPORT

In [8]:
list(df_all.columns)

['accommodates',
 'availability_30',
 'availability_365',
 'availability_90',
 'bedrooms',
 'bed',
 'calculated_host_listings_count',
 'has_availability',
 'host_response_rate',
 'host_response_time',
 'instant_bookable',
 'maximum_nights',
 'neighbourhood_group',
 'price',
 'property_type',
 'room_type',
 'license',
 'bathrooms',
 'air',
 'allowed',
 'cleaning',
 'hot water iron',
 'iron',
 'microwave',
 'parking',
 'refrigerator',
 'shampoo',
 'tv washer',
 'wifi kitchen',
 'and silverware',
 'body',
 'clothing',
 'clothing storage',
 'coffee',
 'elevator',
 'hair',
 'host_identity_verified',
 'host_verifications',
 'kitchen essentials',
 'allowed.1',
 'basics',
 'beds',
 'dryer bed',
 'hair dryer',
 'maker',
 'microwave hangers',
 'oven',
 'stove',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'host_is_superhost',
 'bathrooms_text',
 'precio_m2',
 'latitude',
 'longitude',
 'amenities',
 'number_of_reviews',
 'rentabilidad_predicha',
 'rentable',
 'precio_total',
 'm2',
 'ingresos_brutos_anuales',
 'beneficio_neto_anual',
 'precio_estimado',
 'rentabilidad_anual_pct',
 'periodo',
 'orden_periodo']

In [9]:
df_all[['availability_365', 
        'maximum_nights', 
        'neighbourhood_group', 
        'price', 
        'rentable',
        'property_type',
        'room_type',
        'm2',
        'ingresos_brutos_anuales',
        'beneficio_neto_anual',
        'precio_estimado',
        'rentabilidad_anual_pct']].loc[(df_all.rentabilidad_anual_pct>10)&(df_all.rentable==False)].sort_values('rentabilidad_anual_pct',ascending=False)

,availability_365,maximum_nights,neighbourhood_group,price,rentable,property_type,room_type,m2,ingresos_brutos_anuales,beneficio_neto_anual,precio_estimado,rentabilidad_anual_pct
54695,365,2,Ciudad Lineal,1700.0,False,OTROS,Private room,90,761316.27,532921.39,330840,161.08
29336,365,2,Ciudad Lineal,1700.0,False,OTROS,Private room,90,668709.93,468096.95,330840,141.49
35131,365,365,Ciudad Lineal,1500.0,False,Private room in rental unit,Private room,50,328500.00,229950.00,183800,125.11
60633,365,365,Ciudad Lineal,1500.0,False,Private room in rental unit,Private room,50,328500.00,229950.00,183800,125.11
56286,364,1125,Puente de Vallecas,900.0,False,Private room in rental unit,Private room,50,196560.00,137592.00,118350,116.26
...,...,...,...,...,...,...,...,...,...,...,...,...
40678,353,365,Puente de Vallecas,80.0,False,Entire rental unit,Entire home/apt,50,16944.00,11860.80,118350,10.02
35896,324,730,Latina,102.0,False,Entire rental unit,Entire home/apt,50,19828.80,13880.16,138600,10.01
27121,353,21,Chamberí,315.0,False,OTROS,Entire home/apt,70,66717.00,46701.90,466550,10.01
36544,332,365,Fuencarral,145.0,False,Entire rental unit,Entire home/apt,50,28884.00,20218.80,201900,10.01
46365,353,365,Usera,118.0,False,Entire rental unit,Entire home/apt,70,24992.40,17494.68,174790,10.01

In [10]:
df_all[(df_all.rentabilidad_anual_pct>100)&(df_all.rentable==False)&(df_all.neighbourhood_group=="San Blas")].sort_values('rentabilidad_anual_pct',ascending=False)

,accommodates,availability_30,availability_365,availability_90,bedrooms,bed,calculated_host_listings_count,has_availability,host_response_rate,host_response_time,instant_bookable,maximum_nights,neighbourhood_group,price,property_type,room_type,license,bathrooms,air,allowed,cleaning,hot water iron,iron,microwave,parking,refrigerator,shampoo,tv washer,wifi kitchen,and silverware,body,clothing,clothing storage,coffee,elevator,hair,host_identity_verified,host_verifications,kitchen essentials,allowed.1,basics,beds,dryer bed,hair dryer,maker,microwave hangers,oven,stove,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,host_is_superhost,bathrooms_text,precio_m2,latitude,longitude,amenities,number_of_reviews,rentabilidad_predicha,rentable,precio_total,m2,ingresos_brutos_anuales,beneficio_neto_anual,precio_estimado,rentabilidad_anual_pct,periodo,orden_periodo
29780,2,30,365,90,0.0,0,1,yes,0.0,no response,f,2,San Blas,800.0,Private room in home,Private room,no,1.0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,f,"['email', 'phone']",0,0,0,1.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f,1.0,2996,40.426400,-3.620660,"[""Washer"", ""TV"", ""Shampoo"", ""Air conditioning""...",0,0.023398,False,800.0,40,175200.0,122640.0,119840,102.34,Jun25,3
35397,2,30,365,90,1.0,0,1,yes,0.0,no response,f,365,San Blas,1000.0,Private room in rental unit,Private room,no,1.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,0,0,1.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f,1.0,2996,40.428033,-3.619205,"[""Washer"", ""Kitchen"", ""Wifi"", ""Free parking on...",0,0.009803,False,1000.0,50,219000.0,153300.0,149800,102.34,Jun25,3
55052,2,30,365,90,0.0,0,1,yes,0.0,no response,f,2,San Blas,800.0,Private room in home,Private room,no,1.0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,f,"['email', 'phone']",0,0,0,1.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f,1.0,2996,40.426400,-3.620660,"[""Air conditioning"", ""First aid kit"", ""Hangers...",0,0.023398,False,800.0,40,175200.0,122640.0,119840,102.34,Mar25,2

In [11]:
ruta_salida = ruta_resultados + 'airbnb_all_periodos.csv'
df_all.to_csv(ruta_salida, index=False, decimal='.')
print(f'Exportado: {ruta_salida}')
print(f'Filas totales: {df_all.shape[0]}')
print(f'Columnas: {df_all.shape[1]}')

Exportado: C:/Users/Oscar/OneDrive - FM4/Escritorio/EVOLVE/Data Science/Proyecto-Master-DataScience-Evolve-OscarFraile/05_Resultados/airbnb_all_periodos.csv
Filas totales: 73584
Columnas: 72

In [12]:
df_all

,accommodates,availability_30,availability_365,availability_90,bedrooms,bed,calculated_host_listings_count,has_availability,host_response_rate,host_response_time,instant_bookable,maximum_nights,neighbourhood_group,price,property_type,room_type,license,bathrooms,air,allowed,cleaning,hot water iron,iron,microwave,parking,refrigerator,shampoo,tv washer,wifi kitchen,and silverware,body,clothing,clothing storage,coffee,elevator,hair,host_identity_verified,host_verifications,kitchen essentials,allowed.1,basics,beds,dryer bed,hair dryer,maker,microwave hangers,oven,stove,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,host_is_superhost,bathrooms_text,precio_m2,latitude,longitude,amenities,number_of_reviews,rentabilidad_predicha,rentable,precio_total,m2,ingresos_brutos_anuales,beneficio_neto_anual,precio_estimado,rentabilidad_anual_pct,periodo,orden_periodo
0,1,0,144,0,1.0,1,2,yes,0.0,no response,f,40,Latina,31.0,Private room in rental unit,Private room,no,1.0,1,0,0,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,t,"['email', 'phone']",1,0,1,1.0,1,1,1,1,1,0,4.58,4.72,4.56,4.75,4.82,4.21,4.67,f,1.0,2772,40.403810,-3.741300,"[""First aid kit"", ""Wifi"", ""Kitchen"", ""Essentia...",33,0.995983,True,31.00,50,5138.250,3596.77,138600,2.60,Dic24,1
1,2,0,0,0,1.0,0,3,no,0.0,no response,f,180,Centro,106.0,Entire rental unit,Entire home/apt,no,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,f,"['email', 'phone']",0,0,0,1.0,0,0,0,0,0,0,4.63,4.71,4.88,4.82,4.78,4.90,4.69,f,1.0,6170,40.414760,-3.704180,"[""Heating"", ""Wifi"", ""TV with standard cable"", ...",172,1.000000,True,106.00,50,29017.500,20312.25,308500,6.58,Dic24,1
2,2,0,0,0,1.0,0,1,no,0.0,no response,f,730,Centro,106.0,Entire loft,Entire home/apt,no,1.0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,f,"['email', 'phone']",0,1,0,1.0,0,0,0,0,0,0,4.38,4.14,4.38,4.63,4.63,4.88,4.25,f,1.0,6170,40.412590,-3.701050,"[""Breakfast"", ""Heating"", ""Wifi"", ""Smoking allo...",8,1.000000,True,106.00,50,29017.500,20312.25,308500,6.58,Dic24,1
3,3,0,0,0,1.0,0,3,no,0.0,no response,f,180,Centro,122.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,f,"['email', 'phone']",0,1,0,2.0,0,0,0,0,0,0,4.65,4.69,4.90,4.85,4.79,4.88,4.55,f,1.0,6170,40.422470,-3.705770,"[""Heating"", ""Wifi"", ""Pets allowed"", ""Kitchen"",...",49,1.000000,True,122.00,50,33397.500,23378.25,308500,7.58,Dic24,1
4,4,13,332,59,1.0,0,3,yes,100.0,within an hour,f,30,Centro,69.0,Private room in rental unit,Private room,no,1.5,0,1,1,1,1,0,0,1,1,0,0,1,1,0,0,0,0,1,t,"['email', 'phone']",1,1,1,2.0,0,1,0,0,0,0,4.64,4.78,4.42,4.79,4.85,4.97,4.58,f,1.5,6170,40.418840,-3.696550,"[""Books and reading material"", ""First aid kit""...",219,0.000008,False,80.94,50,2003.265,1402.29,308500,0.45,Dic24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73579,2,20,355,80,1.0,0,45,yes,73.0,within a few hours,f,365,Tetuán,67.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,1,0,1.0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1.0,4536,40.464951,-3.704578,"[""Air conditioning"", ""Pets allowed"", ""Wifi"", ""...",0,0.000018,False,67.00,50,14271.000,9989.70,226800,4.40,Mar25,2
73580,2,25,360,85,1.0,0,45,yes,73.0,within a few hours,f,365,Tetuán,63.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,1,0,1.0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1.0,4536,40.468355,-3.706939,"[""Air conditioning"", ""Pets allowed"", ""Wifi"", ""...",0,0.000009,False,63.00,50,13608.000,9525.60,226800,4.20,Mar25,2
73581,3,0,0,0,1.0,1,3,yes,100.0,within an hour,f,365,Hortaleza,103.0,Entire rental unit,Entire home/apt,no,1.0,1,1,1,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,t,"['email', 'phone']",0,1,1,2.0,0,1,1,0,1,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,t,1.0,4368,40.464110,-3.647130,"[""Cleaning available during stay"", ""Wifi"", ""Wi...",0,1.000000,True,103.00,50,0.000,0.00,218400,0.00,Mar25,2
73582,5,30,365,90,2.0,0,45,yes,73.0,within a few hours,f,365,Carabanchel,100.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,1,0,3.0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1.0,2712,40.395983,-3.730953,"[""Pets allowed"", ""Kitchen"", ""TV"", ""Air conditi...",0,0.000075,False,100.00,70,21900.000,15330.00,189840,8.08,Mar25,2
73583,3,3,3,3,1.0,0,45,yes,73.0,within a few hours,f,365,Carabanchel,66.0,Entire rental unit,Entire home/apt,no,1.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,t,['phone'],0,1,0,1.0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1.0,2712,40.395621,-3.731533,"[""Pets allowed"", ""Kitchen"", ""TV"", ""Air conditi...",0,1.000000,True,66.00,50,118.800,83.16,135600,0.06,Mar25,2